# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.image import Image
from swagger_server import util


class Cart(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, images: List[Image]=None):  # noqa: E501
        """Cart - a model defined in Swagger

        :param user_id: The user_id of this Cart.  # noqa: E501
        :type user_id: str
        :param images: The images of this Cart.  # noqa: E501
        :type images: List[Image]
        """
        self.swagger_types = {
            'user_id': str,
            'images': List[Image]
        }

        self.attribute_map = {
            'user_id': 'userID',
            'images': 'images'
        }

        self._user_id = user_id
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'Cart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Cart of this Cart.  # noqa: E501
        :rtype: Cart
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this Cart.


        :return: The user_id of this Cart.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this Cart.


        :param user_id: The user_id of this Cart.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def images(self) -> List[Image]:
        """Gets the images of this Cart.


        :return: The images of this Cart.
        :rtype: List[Image]
        """
        return self._images

    @images.setter
    def images(self, images: List[Image]):
        """Sets the images of this Cart.


        :param images: The images of this Cart.
        :type images: List[Image]
        """

        self._images = images
